---

- readIn:
    mode: 0                   # 图像模式
    type: 'jpg'               # 主要看是不是raw文件
    raw_size: 3072 
    output_label: 'hello'     # 保存成一个另外的标签
    verbose: true             # 显示处理结果

- print:
    input_label: 'hello'
    mode: 'shape'
    verbose: true

- math:
    input_label: 'hello'
    mode: 'exp'
    power: 2.5
    output_label: 'math'
    verbose: true

- writeOut:
    input_label: 'math'
    suffix: '_math'
    path: './imgs'
    verbose: true
    
- blur:
    input_label: 'math'
    mode: 'median'
    kernel_size: 5
    output_label: 'blur'
    verbose: true

- bilateral:
    input_label: 'blur'
    d: 0
    sigma_color: 20
    sigma_space: 5
    output_label: 'bilateral'
    verbose: true

- writeOut:
    input_label: 'bilateral'
    suffix: '_bi'
    path: './imgs'
    verbose: true

- threshold:
    input_label: 'hello'
    val: 70
    output_label: 'threshold'
    verbose: true

- morphology:
    input_label: 'threshold'
    kernel_size: 5
    run:
        - 
            erode_time: 1
            dilate_time: 1
            times: 1
            res: 0
        - 
            erode_time: 1
            dilate_time: 1
            times: 1
            res: 0
    output_label: 'morphology'

- drawColorHist:
    input_label: 'bilateral'
    channel: 120
    threshold: 50
    smooth: true
    smooth_param: 5
    output_label: 'hist'
    param_out: 'hist'
    verbose: true

- writeOut:
    input_label: 'hist'
    suffix: '_hist'
    path: './imgs'
    verbose: true

- drawContour:
    input_label:    'bilateral'
    max_length:     1000
    min_length:     7
    min_one_size:   45
    one_size:       100
    more_size:      1000
    circle_size:    50000
    mode:           'height' # 另一个是'height'
    output_label:   'contour'
    param_out: 
        count: 'count'
        center: 'center'
    verbose:        true
    
- writeOut:
    input_label: 'hello'
    path: './imgs'
    verbose: true

- writeOut:
    input_label: 'contour'    
    suffix: '_contour'
    path: './imgs'
    verbose: true
        
- writeOut:
    input_label: 'morphology'
    suffix: '_m'
    path: './imgs'
    verbose: true

- tree:
    hello: 'world'

- dump_params:
    hello: 'world'